---
abstract: 'A simple API for handling asynchronous events.'
author:
  - 'Eden Cardim <edencardim@gmail.com>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Deferred
requires:
  Moose: 0
  namespace::autoclean: 0
resources:
  repository: http://github.com/edenc/Object-Deferred.git
version: 0.001
